// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYDa-gsYLVyO2q6fNzhgbTwlpwBgKDvP0',
    appId: '1:195584504433:web:e9374bfd1177eef643e1d0',
    messagingSenderId: '195584504433',
    projectId: 'pollycollebattle-6e2dd',
    authDomain: 'pollycollebattle-6e2dd.firebaseapp.com',
    storageBucket: 'pollycollebattle-6e2dd.appspot.com',
    measurementId: 'G-P7REWSZVGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR0bWEfiTpZNbQtnLqN5u1_obAHrk-Qm4',
    appId: '1:195584504433:android:a9dbe98de74905f343e1d0',
    messagingSenderId: '195584504433',
    projectId: 'pollycollebattle-6e2dd',
    storageBucket: 'pollycollebattle-6e2dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANOAxdeqFC_28-e2BWkdPXtf6BbeWf4Ys',
    appId: '1:195584504433:ios:9cde1c975fcfc8c143e1d0',
    messagingSenderId: '195584504433',
    projectId: 'pollycollebattle-6e2dd',
    storageBucket: 'pollycollebattle-6e2dd.appspot.com',
    iosBundleId: 'com.example.pollyColleBattle231008',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANOAxdeqFC_28-e2BWkdPXtf6BbeWf4Ys',
    appId: '1:195584504433:ios:56a2c5b4c8d701d243e1d0',
    messagingSenderId: '195584504433',
    projectId: 'pollycollebattle-6e2dd',
    storageBucket: 'pollycollebattle-6e2dd.appspot.com',
    iosBundleId: 'com.example.pollyColleBattle.RunnerTests',
  );
}
